# Generated by Django 6.0.4 on 2026-04-13 23:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CronogramaPrazo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_etapa', models.CharField(max_length=100)),
                ('data_limite', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='trabalhotcc',
            name='aceite_orientador',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='trabalhotcc',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meus_tccs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trabalhotcc',
            name='status',
            field=models.CharField(choices=[('SUBMETIDO', 'Aguardando Aprovação'), ('ACEITO', 'Em Orientação'), ('REJEITADO', 'Proposta Rejeitada'), ('DEFESA_AGENDADA', 'Defesa Agendada'), ('CONCLUIDO', 'Concluído')], default='SUBMETIDO', max_length=20),
        ),
        migrations.CreateModel(
            name='AtaOrientacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_reuniao', models.DateField()),
                ('resumo_discussao', models.TextField()),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('trabalho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atas_reuniao', to='core.trabalhotcc')),
            ],
        ),
        migrations.CreateModel(
            name='Banca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_defesa', models.DateTimeField()),
                ('local', models.CharField(max_length=100)),
                ('nota_1', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('nota_2', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('nota_3', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('media_final', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('avaliador_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banca_aval1', to=settings.AUTH_USER_MODEL)),
                ('avaliador_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banca_aval2', to=settings.AUTH_USER_MODEL)),
                ('avaliador_3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banca_aval3', to=settings.AUTH_USER_MODEL)),
                ('trabalho', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='banca', to='core.trabalhotcc')),
            ],
        ),
        migrations.CreateModel(
            name='ChecklistDocumental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termo_autorizacao', models.BooleanField(default=False)),
                ('nada_consta_biblioteca', models.BooleanField(default=False)),
                ('versao_final_entregue', models.BooleanField(default=False)),
                ('trabalho', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='core.trabalhotcc')),
            ],
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='tccs/entregas/')),
                ('descricao', models.CharField(help_text='Ex: Versão inicial, Cap 1, etc.', max_length=100)),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('trabalho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='core.trabalhotcc')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('data_feedback', models.DateTimeField(auto_now_add=True)),
                ('entrega', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='core.entrega')),
                ('orientador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
