# Generated by Django 6.0.4 on 2026-04-14 00:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cronogramaprazo_trabalhotcc_aceite_orientador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banca',
            name='avaliador_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banca_aval1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='banca',
            name='avaliador_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banca_aval2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='banca',
            name='avaliador_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banca_aval3', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='banca',
            name='data_defesa',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='banca',
            name='local',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
