# Generated by Django 6.0.4 on 2026-04-14 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_banca_avaliador_1_alter_banca_avaliador_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='entrega',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='core.entrega'),
        ),
    ]
