# Generated by Django 6.0.4 on 2026-04-17 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_feedback_entrega'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='orientador',
            new_name='autor',
        ),
        migrations.AddField(
            model_name='feedback',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='core.feedback'),
        ),
    ]
